#!/usr/bin/env bash
# Transfers a file from a client to a server

if [ $# -lt 4 ]; then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
	exit 1
fi

FILE_PATH=$1
IP=$2
USERNAME=$3
SSH_PRIV_KEY=$4

scp -o StrictHostKeyChecking=no -i "$SSH_PRIV_KEY" "$FILE_PATH" "$USERNAME@$IP":~/ || { echo "Failed to copy file"; exit 1; }
