#!/usr/bin/env bash
# Generates and creates a compressed MySQL dump archive

file_name=$(date +"%d-%m-%Y").tar.gz

mysqldump -uroot -p"$1" --all-databases > backup.sql
tar -cvzf "$file_name" backup.sql
