#!/usr/bin/env bash
# Displays all active IPv4 IPs on the machine it’s executed on

# First attempt - ifconfig | grep "\binet\b" | cut -d ' ' -f10

# Improvement
ifconfig | grep -Eo "inet\b (addr:)?(([0-9]+)\.?){4}" | cut -d ' ' -f2
