#!/usr/bin/env bash
# Gracefully reloads Gunicorn

# Get the master process ID of Gunicorn
PID=$(pgrep -f 'gunicorn: master')

if [ -n "$PID" ]; then
	# Send the SIGHUP signal to the master process
	kill -HUP "$PID"
	echo "Gunicorn reloaded successfully."
else
	echo "Gunicorn master process not found."
fi
