#!/usr/bin/env bash
# Gracefully reloads Gunicorn

# Get the master process ID of Gunicorn
PID=$(pgrep gunicorn)

if [ -n "$PID" ]; then
	# Send the SIGHUP signal to the process
	kill -HUP "$PID"
	echo "Gunicorn reloaded successfully."
else
	echo "Gunicorn process not found."
fi
