#!/usr/bin/env bash
# Connect to a server via ssh using the private key ~/.ssh/school with the user ubuntu

ssh -i "$HOME/.ssh/school" ubuntu@52.90.15.81 || echo "An error occured while connecting to $HOST"
